import type { Metadata } from 'next'
import '../styles/globals.css';
import {fontClass} from "@/styles/font";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`h-full text-off-black ${fontClass}`} lang="en">
      <body className="h-full text-off-black">{children}</body>
    </html>
  )
}
